### ISSUE TITLE
Models of robot shown during initial calibration

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_areditor#182]
AREditor version 0.10.2

When I start the app and open an existing scene, there are shown models of robots even before I perform the calibration. Other models (collision objects) are properly hidden. The proper state should be that AREditor does not show any objects before calibration. When I perform recalibration, everything is hidden.

![Screenshot_20201106-104513_AREditor](https://user-images.githubusercontent.com/1199396/98540837-cf16a400-228e-11eb-9a99-9a8769e76c6f.jpg)

**Comment by ZdenekM** [comment]
@xBambusekD This is probably also something for you?

**Comment by xBambusekD** [comment]
Fixed. Should be published in next release.
