### ISSUE TITLE
Set negative value from tablet

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_areditor#185]
Please enable to set negative number values in tablet. When I wanted to set positions, orientations or relative positions is not enable to set negative values from tablet.

**Found in version**
Editor version: 0.10.3
Server version: 0.10.1
Editor API version: 0.9.2
Server API version: 0.9.2

**Comment by Kapim** [comment]
I will take a look on that.

**Comment by Kapim** [comment]
On Samsung devices, to type "-" in numerical inputs, you need to hit the "dot" twice. See https://www.youtube.com/watch?v=VF-59l1Qi_M

Please let me know if this solved your issue.
