### ISSUE TITLE
Move to AP not possible if AP is inside collision object

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_areditor#196]
Currently, a safe move is always used when moving to an action point. This might be problematic in some cases (e.g. AP is inside a collision object) and the type of move should be probably selectable.

**Comment by ZdenekM** [comment]
ARServer RPCs now have `safe` parameter (defaulting to True). It was also added to events, so the UI can indicate whether the current movement is safe or unsafe. The PR: https://github.com/robofit/arcor2/pull/451.

**Comment by Kapim** [comment]
Implementad in 0.12.0
