### ISSUE TITLE
Support for Position as action parameter type

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_areditor#242]
Currently, we only support `Pose`, which is stored in a project as a reference to the action point's orientation (position of AP + referenced orientation forms the pose). Right now, even in actions where the position would be enough, the pose has to be used instead, which means that a user has to create an AP with actually useless orientation. This might be less confusing and simpler if we support a `Position` type (a reference to AP instead of its orientation). The support is already prepared in the backend (https://github.com/robofit/arcor2/issues/736).

**Comment by Kapim** [comment]
Added in #245
