### ISSUE TITLE
Allow to align robot with table plane in Project editor

### ISSUE THREAD

**Issue by rstourac** [robofit/arcor2_areditor#59]
**Abstract**
Most of moves in the project require to end with robot aligned with bottom plane as it is plane where almost all accessories are laying. When there is one movement in the project which requires robot to be in different orientation (robot gets disaligned by this) it is hard to align robot again.

**Extension**
Operator wants to be able to align robot whenever he needs when setting AP positions and orientations in Project editor by hitting special button.

**Comment by Kapim** [comment]
Implemented in 0.13.0
